### ISSUE TITLE
Quiz Game business and interface layer

### ISSUE THREAD

**Issue by keremmican** [Kenreks/CSE3044_ProjectGRP40#3]

**Comment by keremmican** [comment]
<img width="190" alt="image" src="https://user-images.githubusercontent.com/47419589/172004036-2373ec46-aca5-487c-a51c-d3ca613921b6.png">
<img width="188" alt="image" src="https://user-images.githubusercontent.com/47419589/172004041-21e9a205-aa6b-4743-9fb0-332da95d25da.png">
<img width="188" alt="image" src="https://user-images.githubusercontent.com/47419589/172004055-44b058a8-a4d6-40ef-99fc-7bd103351fdd.png">
<img width="188" alt="image" src="https://user-images.githubusercontent.com/47419589/172004059-23a8d872-f755-4cf9-99d3-3e72d8d9005c.png">

**Comment by farzel** [comment]
Development process of Quiz Game has successfully finished.

[Quiz_Game.zip](https://github.com/Kenreks/CSE3044_ProjectGRP40/files/8847993/Quiz_Game.zip)
